name: locaobra_mobile
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.12.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_svg: ^2.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0


flutter:
  uses-material-design: true
  assets:
    - assets/Logo_LOCAOBRA.png
    - assets/andaimes.svg
    - assets/dicas.svg
    - assets/elevacao.svg
    - assets/ferramentas.svg
    - assets/interroga.svg
    - assets/pesado.svg
    - assets/img_art1.jpg
    - assets/img_art2.jpg
    - assets/img_art2(1).png
    - assets/homebanner1.png


    